export enum IpcChannel {
  AllowPostponeGet = "ALLOW_POSTPONE_GET",
  AppInitializedSet = "APP_INITIALIZED_SET",
  AppInitializedGet = "APP_INITIALIZED_GET",
  BreakEnd = "BREAK_END",
  BreakLengthGet = "BREAK_LENGTH_GET",
  BreakPostpone = "BREAK_POSTPONE",
  BreakStart = "BREAK_START",
  BreakWindowResize = "BREAK_WINDOW_RESIZE",
  BreakTrackingComplete = "BREAK_TRACKING_COMPLETE",
  Error = "ERROR",
  SoundEndPlay = "SOUND_END_PLAY",
  SoundStartPlay = "SOUND_START_PLAY",
  SettingsGet = "SETTINGS_GET",
  SettingsSet = "SETTINGS_SET",
  TimeSinceLastBreakGet = "TIME_SINCE_LAST_BREAK_GET",
  WasStartedFromTrayGet = "WAS_STARTED_FROM_TRAY_GET",
  TrayStatusGet = "TRAY_STATUS_GET",
  BreakStartNow = "BREAK_START_NOW",
  BreaksEnabledSet = "BREAKS_ENABLED_SET",
  SettingsWindowOpen = "SETTINGS_WINDOW_OPEN",
  TrayPopoverHide = "TRAY_POPOVER_HIDE",
  TrayPopoverResize = "TRAY_POPOVER_RESIZE",
}
